### ISSUE TITLE
Developer BCCP editing and revising functionality

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#777] opened 2020-03-11 20:13 UTC
This issue is created as the first stepping stone for issue #658 . 

This issue covers editing, revising, and state management of BCCP.

**Comment by asdimitriadis** [comment] 2020-03-13 20:28
The issue is that the "Nillable" and the "Default" value fields are mutually exclusive. 

The excepted behavior is that the "Nillable" and the "Default" value fields are not mutually exclusive. (TA1.4 and TA1.5 of TC10.15)

**Comment by asdimitriadis** [comment] 2020-03-13 20:32
One more issue is that when we set (click) the "Nillable" field it returns the message that the BCCP was updated. However, if we open the BCCP again this field is unchecked. So it is not stored.

**Comment by rekuku** [comment] 2020-03-14 03:26
Now it fixed.
Until now `Nillable` was mutually exclusive with `Default` and `Fixed`.
But now `Nillable` is mutually exclusive only `Fixed` value.
So `Value constraint` is not be disabled even if user check `Nillable` as true.
And in situation of Nillable is true, if user check `Fixed` then `Nillable` will be false.

**Comment by asdimitriadis** [comment] 2020-03-16 15:16
When we leave the Definition blank the following message is returned:
"Definition is blank.
Are you want to update?"

I suggest we change it to:
"Definition is blank.
Do you want to update?"

**Comment by asdimitriadis** [comment] 2020-03-16 15:17
Another issue is that the DEN existing in the BCCP tree (at the left pane of the BCCP page) is not changed.
To reproduce the issue:
1. Create a BCCP
2. Change the "Property Term" Field.
3. The DEN in the BCCP tree is not changed.

One more consequence of this is that in the CC List page all BCCPs are displayed with the DEN set as "Property Term"

**Comment by asdimitriadis** [comment] 2020-03-16 15:46
> Another issue is that the DEN existing in the BCCP tree (at the left pane of the BCCP page) is not changed.
> To reproduce the issue:
> 
> 1. Create a BCCP
> 2. Change the "Property Term" Field.
> 3. The DEN in the BCCP tree is not changed.
> 
> One more consequence of this is that in the CC List page all BCCPs are displayed with the DEN set as "Property Term"

The part "One more consequence of this is that in the CC List page all BCCPs are displayed with the DEN set as "Property Term" is fixed.

**Comment by rekuku** [comment] 2020-03-16 16:19
Warning text and tree updates have been fixed.

**Comment by asdimitriadis** [comment] 2020-03-16 17:24
Just to keep track of the comments. All the above mentioned are fixed.

**Comment by asdimitriadis** [comment] 2020-03-17 16:31
We have the following two issues that related to editing a revision of a BCCP. 

1. In a new revision of a BCCP , we should not be able to change the Property Term.

2. In a new revision of a BCCP, we should be able to change the Definition Source 

2. In a new revision of a BCCP, we should not be able to change the BDT.

**Comment by rekuku** [comment] 2020-03-18 01:01
Properties can be change by as follows.
Revised BCCP (revision> 1)
- It can NOT be change BDT.
- it can NOT be change PropertyTerm.
- it can be change Deprecate.
- it can NOT be change Nillable if Nillable checked on previous revision.
- it can be change Nillable if Nillable is NOT checked on previous revision.

Brand-new BCCP (revision = 1)
- It can be change BDT.
- it can be change PropertyTerm.
- it can NOT be change Deprecate.
- it can be change Nillable.

And also Definision Source, Definition, Fixed value, Default Value can be change in any conditions.

Now it can check in develop branch.
@asdimitriadis please check this.
And please let me know if i got something wrong.

**Comment by kbserm** [comment] 2020-03-18 17:37
@rekuku I think you comment above regarding revision > 1 and deprecation is incomplete. Deprecation can only changed from false to true when revision is > 1.

**Comment by asdimitriadis** [comment] 2020-03-18 17:59
The TC document has been updated.

**Comment by asdimitriadis** [comment] 2020-03-19 14:20
The last issue I am facing is the one Serm mentioned about deprecation when the revision is greater than 1. 
In such case, if “Deprecated” is False, it can be changed to True but not vice versa.

**Comment by rekuku** [comment] 2020-03-19 14:56
> Properties can be change by as follows.
> Revised BCCP (revision> 1)
> 
> * It can NOT be change BDT.
> * it can NOT be change PropertyTerm.
> * it can be change Deprecate.
> * it can NOT be change Nillable if Nillable checked on previous revision.
> * it can be change Nillable if Nillable is NOT checked on previous revision.
> 
> Brand-new BCCP (revision = 1)
> 
> * It can be change BDT.
> * it can be change PropertyTerm.
> * it can NOT be change Deprecate.
> * it can be change Nillable.
> 
> And also Definision Source, Definition, Fixed value, Default Value can be change in any conditions.
> 
> Now it can check in develop branch.
> @asdimitriadis please check this.
> And please let me know if i got something wrong.

As @Serm mentioned
revision > 1
 - The deprecated value only allows false -> true.
And TC 10.21 are applied.
> 1.2 If a fixed value is already applied, it cannot be changed (hence neither default nor nillable can change).

@asdimitriadis Please check this.

**Comment by asdimitriadis** [comment] 2020-03-23 19:37
Now, we cannot set the Default value if we have set Fixed value before.
To reproduce it,
1. Set Default value
2. Click update
3. Set Fixed value
4. Click Update
The value is not stored. However, if I set Fixed value again and click update again is stored.

**Comment by rekuku** [comment] 2020-03-26 19:00
@asdimitriadis I fixed it because there was a problem with the mutual exclusion logic. 
Please test Fixed and Default values.

**Comment by asdimitriadis** [comment] 2020-03-30 15:00
Tested. Everything works.

**Comment by kbserm** [comment] 2020-03-30 16:20
@rekuku @asdimitriadis We need to fix one business rule regarding BCCP. If a fixed value is set in a prior revision, it cannot be changed in a new revision. Because the schema will be backwardly incompatible.

**Comment by asdimitriadis** [comment] 2020-04-06 22:36
The BSCCP should contain a field with the Namespace. The default value of the field should be null.

**Comment by rekuku** [comment] 2020-04-12 23:02
@asdimitriadis Namespace Id field added.

**Comment by kbserm** [comment] 2020-06-12 00:52
When selecting a BDT, I would like to have unqualified BDT as the first set of BDT choices. 

In other words, I would like the dialog to have a filter for types of BDTs and the filter is defaulted to Unqualified BDT. Please see footnote of TC 10.18 where I said we need to add more types to DT Type column.

The reason for doing this is I would like to semi enforce the developer to use only unqualified BDT.

**Comment by asdimitriadis** [comment] 2020-06-12 15:59
In addition, the developer should be able cancel the revision. In this case, the system rollbacks the BCCP to the previous revision. There must be a confirmation dialog box. History of changes can still be kept

**Comment by asdimitriadis** [comment] 2020-06-12 16:24
The issue is that we cannot set the Namespace to "-" value anymore.
The expected behavior is that we can set the Namespace to "-"

**Comment by kbserm** [comment] 2020-06-13 11:28
FYI, I am changing req related to nmsp. it is required for all CC's.  i also made it not revisable.

**Comment by hakjuoh** [comment] 2020-06-17 21:26
> When selecting a BDT, I would like to have unqualified BDT as the first set of BDT choices.
> 
> In other words, I would like the dialog to have a filter for types of BDTs and the filter is defaulted to Unqualified BDT. Please see footnote of TC 10.18 where I said we need to add more types to DT Type column.
> 
> The reason for doing this is I would like to semi enforce the developer to use only unqualified BDT.

@kbserm Since we don't have a column to distinguish between unqualified BDTs and qualified BDTs in `dt` table, we have two options; putting new column into the table or hard-coded those in source codes. I'm not sure if other standards have unqualified BDTs. If you think that unqualified BDTs are OAGIS specific DTs, hard-coding would be simple.

**Comment by kbserm** [comment] 2020-06-18 13:17
@hakjuoh I am fine with putting that only on the UI for now. We might need to revisit this when there is a BDT management functionality. @asdimitriadis Can you note this in the TC doc where this requirement is.

**Comment by asdimitriadis** [comment] 2020-08-24 15:47
**The field Property Term of a BCCP cannot be left blank**

The issue is that the Property Term of a BCCP can be left blank.
To reproduce the issue:
1. Create a BCCP
2. Clear the Property Term field
3. Click the update button

To be consistent, I recommend to disable the Update button if the Property term is left bank and red color the Property Term input field.

**Comment by asdimitriadis** [comment] 2020-08-24 15:50
**The Namespace cannot be left black**
The issue is that the namespace input field can be left blank

To reproduce the issue:
1. Create a BCCP
2. Leave empty the Namespace selector field or choose the "-" option.
3. Click the update button

The expected behavior is that the Namespace field should be one of the available Namespaces.
To be consistent, I recommend to disable the Update button if the Namespace field is left bank or "-" and red color the Namespace field.

**Comment by asdimitriadis** [comment] 2020-08-24 15:51
**The Namespace of a revised (rev >1) BCCP cannot be changed**

The issue is that we can change the Namespace field of a BCCP that its revision is greater than 1.
To reproduce the issue:
1. Revise a published BCCP
2. Change its Namespace

The Namespace field should be disabled.

**Comment by asdimitriadis** [comment] 2020-08-24 15:57
**An ACC which has a descendant ACC that uses a deleted BCCP should be flagged as it is in invalid state**

The issue is that upon opening an ancestor ACC that has an ACC that uses a deleted BCCP, the descendant ACC should be flagged as it is in an invalid state.
To reproduce the issue:
1. Create the BCCP1
2. Create the ACCdescendant  
3. Append the BCCP1 to the ACCdescendant
4. Create the ASCCP1 using the ACCdescendant
5. Create the ACCancestor
6. Append the ASCCP1 to the ACCancestor
7. Open the BCCP1 and delete it
8. Open the ACCancestor
9. Expand the ACCancestor node
10. Expand the ASCCP1 node

At this point the ACCdescendant is not flagged as it is in invalid state.
The expected behavior is that it should be flagged as it is invalid state.

For more information please check TA 3 of the TC 10.23

**Comment by asdimitriadis** [comment] 2020-08-24 15:59
**Deleted BCCP under ACC should have a link to open it in a new tab**

The issue is that upon opening an ACC that has a BCC using a deleted BCCP, the BCCP does not have a link to allow the developer to open the deleted BCCP in another tab so that he can restore it back.

To reproduce the issue:
1. Create the BCCP1
2. Create the ACC1
3. Append the BCCP1 to the ACC1
4. Open the BCCP1 and delete it
5. Open the ACC1
6. Expand the ACC1 root node
7. Click the BCCP1

The BCCP1 is not opened in a new tab. 
The expected behavior is that when we click the BCCP1 it should be opened in a new tab.

For more information please check TA 3 of the TC 10.23

**Comment by asdimitriadis** [comment] 2020-08-24 16:03
**A developer cannot restore a deleted BCCP owned by another developer**

The issue is that a developer cannot restore a deleted BCCP owned by another developer

To reproduce the issue:
1. Login in as developer devx
2. Create BCCP1 and delete it
3. Logout
4. Login as oagis
5. Open BCCP1 and try to restore it

The "Restore" button is disabled.

The expected behavior is that a developer should be able to restore a deleted BCCP owned by another developer. In this case, the ownership is transferred as well.

**Comment by rekuku** [comment] 2020-08-26 04:10
> **The field Property Term of a BCCP cannot be left blank**
> 
> The issue is that the Property Term of a BCCP can be left blank.
> To reproduce the issue:
> 
> 1. Create a BCCP
> 2. Clear the Property Term field
> 3. Click the update button
> 
> To be consistent, I recommend to disable the Update button if the Property term is left bank and red color the Property Term input field.



> **The Namespace cannot be left black**
> The issue is that the namespace input field can be left blank
> 
> To reproduce the issue:
> 
> 1. Create a BCCP
> 2. Leave empty the Namespace selector field or choose the "-" option.
> 3. Click the update button
> 
> The expected behavior is that the Namespace field should be one of the available Namespaces.
> To be consistent, I recommend to disable the Update button if the Namespace field is left bank or "-" and red color the Namespace field.



> **The Namespace of a revised (rev >1) BCCP cannot be changed**
> 
> The issue is that we can change the Namespace field of a BCCP that its revision is greater than 1.
> To reproduce the issue:
> 
> 1. Revise a published BCCP
> 2. Change its Namespace
> 
> The Namespace field should be disabled.

This issues are fixed. @asdimitriadis 



> **Deleted BCCP under ACC should have a link to open it in a new tab**
> 
> The issue is that upon opening an ACC that has a BCC using a deleted BCCP, the BCCP does not have a link to allow the developer to open the deleted BCCP in another tab so that he can restore it back.
> 
> To reproduce the issue:
> 
> 1. Create the BCCP1
> 2. Create the ACC1
> 3. Append the BCCP1 to the ACC1
> 4. Open the BCCP1 and delete it
> 5. Open the ACC1
> 6. Expand the ACC1 root node
> 7. Click the BCCP1
> 
> The BCCP1 is not opened in a new tab.
> The expected behavior is that when we click the BCCP1 it should be opened in a new tab.
> 
> For more information please check TA 3 of the TC 10.23



> **A developer cannot restore a deleted BCCP owned by another developer**
> 
> The issue is that a developer cannot restore a deleted BCCP owned by another developer
> 
> To reproduce the issue:
> 
> 1. Login in as developer devx
> 2. Create BCCP1 and delete it
> 3. Logout
> 4. Login as oagis
> 5. Open BCCP1 and try to restore it
> 
> The "Restore" button is disabled.
> 
> The expected behavior is that a developer should be able to restore a deleted BCCP owned by another developer. In this case, the ownership is transferred as well.

<img width="710" alt="Screen Shot 2020-08-26 at 12 06 29 AM" src="https://user-images.githubusercontent.com/10194354/91254297-006fe100-e730-11ea-881b-d0cbe8740b47.png">

You can see the deleted associations with stroke line and it also have "Open in new tab" context menu.
How about this menu and UI? @asdimitriadis

**Comment by asdimitriadis** [comment] 2020-09-08 15:18
Everything works good. 

The "Open in new tab" option under the menu was tested as well and it works.

**Closed by asdimitriadis** 2020-09-08 15:18 UTC
Labels: enhancement
