### ISSUE TITLE
Developer ASCCP Editing and Revising

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#779] opened 2020-03-12 01:53 UTC
This issue is created as the 3rd stepping stone for issue #658 .

This issue covers editing, revising, and state management of ASCCP.

**Comment by rekuku** [comment] 2020-03-28 14:44
@asdimitriadis I applied TC 10.11 to 10.15. Please test this.

**Comment by asdimitriadis** [comment] 2020-04-06 22:37
The ASCCP should contain Namespace field with the default value of "null"

**Comment by rekuku** [comment] 2020-04-12 23:02
@asdimitriadis Namespace Id field added.

**Comment by asdimitriadis** [comment] 2020-06-01 13:30
The issue is that when a developer moves an ASCCP from WIP to draft or from Draft to Candidate and that ASCCP uses an ACC owned by the same developer there is no message asking him if he wants to move the base ACC to Draft or Candidate respectively. 

The expected behavior is that if a developer moves an ASCCP from WIP to Draft and he owns its base ACC, which is in WIP state as well, then there should be a message asking him if he wants to move the ACC from WIP to Draft.
Also, if a developer moves an ASCCP from Draft to Candidate and he owns its base ACC, which is in Draft state, then there should be a message asking him if he wants to move the ACC from Draft to Candidate.

**Comment by asdimitriadis** [comment] 2020-06-08 18:24
Should we also present the "Select ACC to update ASCCP" dialog in full screen as we do with the other dialogs (e.g., "Select ACC to set a base ACC", "Select a CC property to append an association")?

**Comment by asdimitriadis** [comment] 2020-06-12 11:20
The issue is that if we change the ACC used by a ASCCP, the DEN of all other ASCCs which uses the ASCCP are not updated.
To reproduce the issue:
1.       Create ASCCP1 using ACC1.
2.       Create ACC2 and append ASCCP1.
3.       Change Object Class term of ACC1.
4.       Open ACC2, check that ASCC1 DEN has not been updated accordingly.

The expected behavior is that when the ASCCP DEN changes, all ASCCs which uses the ASCCP and whose revision numbers are 1 shall have their DEN updated accordingly

**Comment by hakjuoh** [comment] 2020-06-12 15:40
> The issue is that if we change the ACC used by a ASCCP, the DEN of all other ASCCs which uses the ASCCP are not updated.
> To reproduce the issue:
> 
> 1. Create ASCCP1 using ACC1.
> 2. Create ACC2 and append ASCCP1.
> 3. Change Object Class term of ACC1.
> 4. Open ACC2, check that ASCC1 DEN has not been updated accordingly.
> 
> The expected behavior is that when the ASCCP DEN changes, all ASCCs which uses the ASCCP and whose revision numbers are 1 shall have their DEN updated accordingly

It's fixed now. The following is a result after 'ACC 1' changes 'ACC 1 (Change)'.
<img width="763" alt="Screen Shot 2020-06-12 at 11 38 21 AM" src="https://user-images.githubusercontent.com/16102116/84520355-702e0e00-aca1-11ea-9657-b7d593fc52f5.png">

**Comment by asdimitriadis** [comment] 2020-06-12 15:58
Also, the developer should be able cancel the revision. In this case, the system rollbacks the ASCCP to the previous revision. There must be a confirmation dialog box. History of changes can still be kept

**Comment by asdimitriadis** [comment] 2020-06-12 16:19
The issue is that we cannot set the Namespace to "-" value anymore.
The expected behavior is that we can set the Namespace to "-"

**Comment by asdimitriadis** [comment] 2020-06-12 17:50
One more issue that affects the transition of an ASCCP from WIP->Draft or from Draft to Candidate.


The developer can change the ASCCP state from WIP to Draft. However the issue is that if the ACC used by the ASCCP is in WIP and owned by the same developer, there is no dialog asking the developer if he wants to move the ACC to Draft as well. The same issue exists if the developer moves the ASCCP to the Candidate state.
The expected behavior is that if a developer moves an ASCCP from WIP to Draft and if he owns the ACC used by the ASCCP and it is in WIP state then there should be a dialog asking him if he wants to move the ACC to draft state as well. The same should happen if the developer moves the ASCCP from Draft to Candidate.

**Comment by hakjuoh** [comment] 2020-06-12 18:10
> The issue is that we cannot set the Namespace to "-" value anymore.
> The expected behavior is that we can set the Namespace to "-"

Now it works for both ASCCP and BCCP

**Comment by hakjuoh** [comment] 2020-06-12 18:26
> One more issue that affects the transition of an ASCCP from WIP->Draft or from Draft to Candidate.
> 
> The developer can change the ASCCP state from WIP to Draft. However the issue is that if the ACC used by the ASCCP is in WIP and owned by the same developer, there is no dialog asking the developer if he wants to move the ACC to Draft as well. The same issue exists if the developer moves the ASCCP from Draft to the Candidate state.
> The expected behavior is that if a developer moves an ASCCP from WIP to Draft and if he owns the ACC used by the ASCCP and it is in WIP state then there should be a dialog asking him if he wants to move the ACC from WIP to Draft state as well. The same should happen if the developer moves the ASCCP from Draft to Candidate.

@kbserm @asdimitriadis This behavior may need to re-consider. After @rekuku and I discussed about this chain responsibility, we decided that transition state function should affect to only target core component per se to make it simpler. For instance, the user has [... -> ACC 1 -> ASCC 1 -> ASCCP 1 -> ACC 2 -> ASCC 2 -> ASCCP 2 -> ... ] chain of components. If he wants to transit the state of ACC 2, it needs to check all components all relationships both left and right directions. Let's talk this at the future meeting.

**Comment by kbserm** [comment] 2020-06-13 11:23
let's skip this feature for now. I noted this in test case doc

**Comment by asdimitriadis** [comment] 2020-06-22 12:42
The DEN field is not updated when we change the Property Term field.
To reproduce the issue,
1. Create an ASCCP
2. Change the Property Term field
3. Click the Update button
4. Check the Property Term against the DEN field. DEN field does not reflect the changes.

**Comment by asdimitriadis** [comment] 2020-06-22 12:51
> The issue is that we cannot set the Namespace to "-" value anymore.
> The expected behavior is that we can set the Namespace to "-"

This should be changed.
The Namespace is required and cannot be null (it should be one of the available namespaces of the drop down list).

**Comment by asdimitriadis** [comment] 2020-08-24 16:48
The above issue that the Namespace is required and cannot be null neither "-" still exists.

**Comment by asdimitriadis** [comment] 2020-08-24 17:44
**The Property Term field cannot be left blank**

The issue is that when we edit an ASCCP, we can clear the Property Term field and Update the ASCCP.
To reproduce the issue:
1. Create a new ASCCP
2. Clear the Property Term field and Update it.

The expected behavior is the the Property Term field cannot be left blank.
To be consistent, I recommend to disable the Update button if the Property term field is left bank and red color the Property Term input field.

**Comment by rekuku** [comment] 2020-08-26 04:11
> > The issue is that we cannot set the Namespace to "-" value anymore.
> > The expected behavior is that we can set the Namespace to "-"
> 
> This should be changed.
> The Namespace is required and cannot be null (it should be one of the available namespaces of the drop down list).



> The above issue that the Namespace is required and cannot be null neither "-" still exists.



> **The Property Term field cannot be left blank**
> 
> The issue is that when we edit an ASCCP, we can clear the Property Term field and Update the ASCCP.
> To reproduce the issue:
> 
> 1. Create a new ASCCP
> 2. Clear the Property Term field and Update it.
> 
> The expected behavior is the the Property Term field cannot be left blank.
> To be consistent, I recommend to disable the Update button if the Property term field is left bank and red color the Property Term input field.

This issues fixed @asdimitriadis.
Please test this on develop branch.

**Comment by asdimitriadis** [comment] 2020-09-08 15:21
Tested and it works good.

**Closed by asdimitriadis** 2020-09-08 15:21 UTC
Labels: enhancement
