### ISSUE TITLE
Developer ACC Editing and Revising 

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#778] opened 2020-03-12 01:24 UTC
This issue is created as the second stepping stone for issue #658 .

This issue covers editing, revising, and state management of ACC. It does not include managing associations within the ACC.

**Comment by asdimitriadis** [comment] 2020-03-19 14:24
The issue is related to editing a brand-new ACC (revision =1) and Abstract (abstract checkbox)

If we set the Component Type to Extension or Semantic Group the Abstract should be False and Disabled.
(TA1.2 of TC10.6 "1.2 Abstract can only be true when the Component Type is base or Semantics.")

**Comment by asdimitriadis** [comment] 2020-03-19 14:33
One more issue is that if the Component Type is "Base" then the Abstract must be True (the checkbox should be checked and Disabled)

**Comment by rekuku** [comment] 2020-03-26 19:03
@asdimitriadis Test Case 10.2 and 10.3 were applied.
Please test this.

**Comment by asdimitriadis** [comment] 2020-03-31 17:59
This issue above-mentioned still exists:
"One more issue is that if the Component Type is "Base" then the Abstract must be True (the checkbox should be checked and Disabled)"

**Comment by asdimitriadis** [comment] 2020-03-31 18:14
Also two more issues:

- An exception is returned when we try to update an ACC having left the Namespace Null ("-").
- When we change the Component type from Semantics to something else (e.g., Abstract) and Update it, it returns back to Semantics.

**Comment by rekuku** [comment] 2020-04-02 16:14
The OagisComponentType currently supported by our system is as follows.
0 = BASE
1 = SEMANTICS
2 = EXTENSION
3 = SEMANTIC_GROUP
4 = USER_EXTENSION_GROUP
5 = EMBEDDED
6 = OAGIS10Nouns
7 = OAGIS10BODs

And the actions that can be taken in each case are as follows.
<TYPE // Value of Abstract // Enable to change Abstract>
- BASE // True // disable
- SEMANTICS // True or False // enable
- EXTENSION // False // disable
- SEMANTIC_GROUP // False // disable
- USER_EXTENSION_GROUP // False // disable
- EMBEDDED // False // disable
- OAGIS10Nouns // False // disable
- OAGIS10BODs // False // disable

As above, "Abstract" can only be changed by users in “SEMANTICS" case.

And "USER_EXTENSION_GROUP, EMBEDDED, OAGIS10Nouns, OAGIS10BODs” has blocked from user's choosing "ComponentType.”
Is this correct? @kbserm 

Please let me know if there is anything to add or change.

@asdimitriadis I fixed three issues what you mentioned.
 - An exception is returned when we try to update an ACC having left the Namespace Null ("-").
 - When we change the Component type from Semantics to something else (e.g., Abstract) and Update it, it returns back to Semantics.
 - One more issue is that if the Component Type is "Base" then the Abstract must be True (the checkbox should be checked and Disabled)
Please test this.

**Comment by asdimitriadis** [comment] 2020-04-02 18:34
They are all fixed.
The last two issues are:

1. We cannot retract an ACC, namely we cannot move it **from Candidate back to WIP state** (the button is disabled). The expected behavior is that we can move an ACC from Candidate state back to WIP state.
2. When a developer revises an ACC (a CC in general), he/she should take the ownership of that revised ACC. The issue is that in current version the ownership remains to the first owner. The expected behavior is that the ownership is transferred to the developer that is revising the ACC. (Note that this second issue is applied to any CC being revised).

**Comment by rekuku** [comment] 2020-04-02 21:04
@asdimitriadis I fixed this issues. Please test this.
```
We cannot retract an ACC, namely we cannot move it from Candidate back to WIP state (the button is disabled). The expected behavior is that we can move an ACC from Candidate state back to WIP state.
When a developer revises an ACC (a CC in general), he/she should take the ownership of that revised ACC. The issue is that in current version the ownership remains to the first owner. The expected behavior is that the ownership is transferred to the developer that is revising the ACC. (Note that this second issue is applied to any CC being revised).
```

**Comment by asdimitriadis** [comment] 2020-04-15 14:47
When we change the "Definition source" we cannot update an ACC. The "Update" button is disabled.

**Comment by hakjuoh** [comment] 2020-04-15 16:18
> When we change the "Definition source" we cannot update an ACC. The "Update" button is disabled.

Please test this again with the latest code.

**Comment by kbserm** [comment] 2020-04-16 19:39
I want to change two business rules related to Editing a revision (>1) of the ACC. 1) Component Type can't b changed. 2) Abstract can only be change from True to False (except the case of Component Type is base)

**Comment by rekuku** [comment] 2020-04-16 21:27
@asdimitriadis 
```
I want to change two business rules related to Editing a revision (>1) of the ACC. 1) Component Type can't b changed. 2) Abstract can only be change from True to False (except the case of Component Type is base)
```
This have applied. Please test this.

**Comment by dubnemo** [comment] 2020-05-04 16:07
@asdimitriadis @kbserm @hakjuoh 
On the Test Server, I tried creating a new ACC which I wanted to call Worker, selected Person. Details ACC as its base, edited the DEN and definition, tried to Save, but got the dreaded HTTP 500 response code.  
Is this just the current state, or should I create a new issue?
I expect to be able to add other components to the new ACC too.

**Comment by rekuku** [comment] 2020-05-04 16:25
@dubnemo 
I uploaded a version that fixed the problem.
Now you can use it normally.
The test server is in development, so there may be unexpected bugs or malfunctions.
If you leave a comment on a slack or issue, we will quickly check and take action.

**Comment by dubnemo** [comment] 2020-05-04 16:47
@rekuku  thank you, that fixed the problem.  I thought your ci/cd process targets test.oagiscore.net.  It should **NOT** target biopharma.oagiscore.net - the latter holds our SME WG BIEs...
@kbserm @hakjuoh

**Comment by rekuku** [comment] 2020-05-04 16:52
Yes, it is. @dubnemo 
"test" and "biopharma" are operating independently of each other,
Only test.oagiscore.net is used for development purposes.

**Comment by kbserm** [comment] 2020-05-29 15:50
Test Assertions 2 - 4 in TC 10.6 needs to be deleted.

**Comment by asdimitriadis** [comment] 2020-06-01 13:20
The issue is that if the "Reusable" field is True in an ASCCP (e.g., Promotion Reference), it cannot be changed when we create a new revision (e.g., revision number 2). The expected behavior is that when the “Reusable” is true in the previous revision, it cannot be changed (it should be checked and disabled).

**Comment by asdimitriadis** [comment] 2020-06-01 13:29
The issue is that when a developer moves an ASCCP from WIP to draft or from Draft to Candidate and that ASCCP uses an ACC owned by the same developer there is no message asking him if he wants to move the base ACC to Draft or Candidate respectively. 

The expected behavior is that if a developer moves an ASCCP from WIP to Draft and he owns its base ACC, which is in WIP state as well, then there should be a message asking him if he wants to move the ACC from WIP to Draft.
Also, if a developer moves an ASCCP from Draft to Candidate and he owns its base ACC, which is in Draft state, then there should be a message asking him if he wants to move the ACC from Draft to Candidate.

**Comment by rekuku** [comment] 2020-06-01 22:58
@asdimitriadis It fixed please test this.

**Comment by asdimitriadis** [comment] 2020-06-08 13:50
The above issue has been fixed and testing.

One more issue (I put it here but it is generic).
The issue is that when we select a non-working branch in the CC list page the buttons used to create CCs are still displayed. Before we did not display them.
So I suggest (if you agree) to hide or disabled these buttons if a non-working branch is selected.

**Comment by hakjuoh** [comment] 2020-06-13 14:45
> The above issue has been fixed and testing.
> 
> One more issue (I put it here but it is generic).
> The issue is that when we select a non-working branch in the CC list page the buttons used to create CCs are still displayed. Before we did not display them.
> So I suggest (if you agree) to hide or disabled these buttons if a non-working branch is selected.

It applied.

**Comment by asdimitriadis** [comment] 2020-06-22 12:56
The above issue is fixed.
One issue is that we should change the Namespace.
The Namespace is required and it should be one of the available Namespaces. (i.e., it cannot be null or "-")

**Comment by kbserm** [comment] 2020-06-25 12:54
Here is my current thought about OAGIS Extension component type. Developer cannot it create it. I'm leaning toward creating it automatically but the developer can choose to remove it.

**Comment by kbserm** [comment] 2020-08-07 23:28
There is no option to remove based ACC. In addition, normally ACC node only shows Object Class Term. But after I set based ACC, the whole DEN is shown.

![image](https://user-images.githubusercontent.com/7863166/89696026-15511580-d8e4-11ea-89f2-266117383051.png)

**Comment by kbserm** [comment] 2020-08-07 23:33
It looks deleted CCs (seem to affect all types of CCs) do not show up on the CC list, unless I chose the Deleted filter.

**Comment by asdimitriadis** [comment] 2020-08-10 14:27
> he above issue is fixed.
> One issue is that we should change the Namespace.
> The Namespace is required and it should be one of the available Namespaces. (i.e., it cannot be null or "-")

This issue happens again.

**Comment by asdimitriadis** [comment] 2020-08-10 14:30
Another issue is that the base ACC **cannot** be a Group, User Extension Group, Embedded.
One example to reproduce the issue is:
1. Create an ACC
2. Set Base ACC the "Any Structured Content. Details" or the "Ledger Amount Group. Details"

**Comment by asdimitriadis** [comment] 2020-08-10 14:35
> There is no option to remove based ACC. In addition, normally ACC node only shows Object Class Term. But after I set based ACC, the whole DEN is shown.
> 
> ![image](https://user-images.githubusercontent.com/7863166/89696026-15511580-d8e4-11ea-89f2-266117383051.png)

You can remove the base ACC using this button,

![bbase](https://user-images.githubusercontent.com/37205288/89794523-2a50c300-daf5-11ea-971d-ef0564e4fff1.jpg)

**Comment by asdimitriadis** [comment] 2020-08-10 15:20
The issue is that we can set a base ACC that contains an ASCCP or a BCCP with the same property term as that already exists in the ACC (property uniqueness)

An example to reproduce the issue is:
1. Create the ACCbase
2. Append the ASCCP "Account Identifiers"
3. Create the ACC1
4. Append the ASCCP "Account Identifiers"
5. Set as base ACC the ACCbase


One question that is arise is what happens if the ACCbase meet the property uniqueness before setting it as a base, but after violates it.
An example to the forenamed question is:
1. Create the ACCbase
2. Create the ACC1
3. Append the ASCCP "Account Identifiers"
4. Set as base ACC the ACCbase
5. Open the ACCbase
6. **Append** the ASCCP "Account Identifiers"**??**

**Comment by hakjuoh** [comment] 2020-08-10 18:25
@kbserm @asdimitriadis As we know, this one probably relates to the synchoronous/asynchronous validation as we did in release management. I have a plan to upgrade the database to MySQL 8 to get provided CTE feature which allows hierarchical queries that may help to traverse CC trees.

**Comment by kbserm** [comment] 2020-08-11 17:56
@hakjuoh let's plan to implement this in CC validation, even with hierarchical query the validation will be faster which is good. 

As for @asdimitriadis second question, all these will be reported in after the validation.

**Closed** 2020-08-31 19:42 UTC
Labels: enhancement
