### ISSUE TITLE
Developer ACC Association Management

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#780] opened 2020-03-12 01:55 UTC
This issue is created as the 4th stepping stone for issue #658 .

This issue deals with managing associations within the ACC.

**Comment by asdimitriadis** [comment] 2020-05-18 14:50
The issue is that if the Object Class Term of an ACC changes, then the DEN of the ASCCP which depend on it does not change.
The expected behavior is that if the OCT of an ACC changes, then the DEN of the ASCCPs which depend of it should change accordingly.

**Comment by rekuku** [comment] 2020-05-18 15:27
@asdimitriadis Thank you.
It has been fixed. please pull the gateway codes.

**Comment by asdimitriadis** [comment] 2020-06-08 13:46
The above issue has been fixed and tested.
Below I add some more issues:

1. The issue is that when we remove an association (ASCC or BCC) of an ACC there is no confirmation dialog box. The expected behavior is that when we remove an association of an ACC there must be a confirmation dialog box to confirm our intention. 

2. The issue is that we can set a base ACC, whose Component Type is Embedded (e.g., the ACC "Any Structure Content"), to an ACC. The expected behavior is that we cannot set a base ACC whose component type is Group, UEG, or Embedded. Maybe the ACCs whose Component Type is any of the aforementioned should not be displayed in the dialog used to choose the base ACC.

3. The issue is that we can change the details (i.e., the fields) of a base ACC. The expected behavior is that we cannot change the fields of the base ACC.

4. The issue is that we can set an ACC as a base to an ACC that aldready contains an ASCCP or a BCCP with the same property term. To reproduce the issue:
         i. Create an ACC
         ii. Append the ASCCP "Allocate Resource. Allocate Resource"
         iii. Set as a base ACC the "Change Acknowledge Allocate Resource Data Area"
         iv. You will notice that it was successufully set.

The expected behavior is that the base ACC should not contain an ASCCP or a BCCP with the same property term with an existing association.

5. The issue is that if a developer (e.g.,devx) transfer the ownership of an ACC to another developer (e.g., devy) then the ownership of the associations of the ACC is not tranferred. 
The expected behavior is that if a developer (e.g.,devx) transfer the ownership of an ACC to another developer (e.g., devy) then the ownership of the associations (ASCCPs and BCCPs) of the ACC should be tranferred. (Note that the ownership is transferred only in CCs which are in WIP state) 

6. The issue is that when we delete an ACC that has some deleted associations, they are not restored back and they remain deleted. 
The expected behavior is that when we restore an ACC then all of its deleted associations should be restored as well.

**Comment by kbserm** [comment] 2020-06-09 11:26
@asdimitriadis for #4 please make sure to test the case where:
a) the based ACC has a group ACC which has a property P, the ACC cannot have the property P
b) same condition as (a), but the user tries to add an assoc to a group ACC containing the property P. this should not be allowed as well.

**Comment by kbserm** [comment] 2020-08-06 13:46
@rekuku the pop-up dialog for selecting a bccp or asccp, when appending property, should allow the user to click on the bccp or asccp to open its detail in the new tab.

**Comment by kbserm** [comment] 2020-08-08 12:13
Append always means "add to the end/last". So menu items "Append Property Before" and "Append Property at First" do not make sense. They should be "Insert Property Before" and "Insert Property at First". "Append Property After" is also iffy, "Insert Property After" reads better. "Append Property at Last" is okay.

**Comment by asdimitriadis** [comment] 2020-08-24 15:46
The issue is that we cannot discard a revision of an ACC if we have appended some associations.
To reproduce the issue
1. Open an ACC which is in Published state
2. Create a new revision
3. Fill the Definition Source and Definition fields
4. Update the ACC
5. Append an ASCCP and a BCCP
6. Click the "Discard Revision" button. 

An error is returned with the exception "java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row:"

**Comment by rekuku** [comment] 2020-08-26 20:37
The above issue has been fixed and tested.
Below I add some more issues:

1. The issue is that when we remove an association (ASCC or BCC) of an ACC there is no confirmation dialog box. The expected behavior is that when we remove an association of an ACC there must be a confirmation dialog box to confirm our intention.
KWANGHOON: I was add confirmation dialog box for set/delete associations and based ACC

2. The issue is that we can set a base ACC, whose Component Type is Embedded (e.g., the ACC "Any Structure Content"), to an ACC. The expected behavior is that we cannot set a base ACC whose component type is Group, UEG, or Embedded. Maybe the ACCs whose Component Type is any of the aforementioned should not be displayed in the dialog used to choose the base ACC.
KWANGHOON: Based ACC selection dialog only show Base, Semantics types of ACC.


3. The issue is that we can change the details (i.e., the fields) of a base ACC. The expected behavior is that we cannot change the fields of the base ACC.
KWANGHOON: Fixed.

4. The issue is that we can set an ACC as a base to an ACC that aldready contains an ASCCP or a BCCP with the same property term. To reproduce the issue:
    i. Create an ACC
    ii. Append the ASCCP "Allocate Resource. Allocate Resource"
    iii. Set as a base ACC the "Change Acknowledge Allocate Resource Data Area"
    iv. You will notice that it was successufully set.
 
 The expected behavior is that the base ACC should not contain an ASCCP or a BCCP with the same property term with an existing association.
 KWANGHOON: Now, when appending association or setting based ACC, it will be display an error message if there are any duplicates.

 
 5. The issue is that if a developer (e.g.,devx) transfer the ownership of an ACC to another developer (e.g., devy) then the ownership of the associations of the ACC is not tranferred.
>    The expected behavior is that if a developer (e.g.,devx) transfer the ownership of an ACC to another developer (e.g., devy) then the ownership of the associations (ASCCPs and BCCPs) of the ACC should be tranferred. (Note that the ownership is transferred only in CCs which are in WIP state)
 KWANGHOON: It fixed. please test this.


 6. The issue is that when we restore a deleted ACC that has some deleted associations, they are not restored back and they remain deleted.
    The expected behavior is that when a developer restores an ACC then all of its deleted associations should be restored as well. (Note that if a developer (e.g., devx) restores back a deleted ACC belonging to another developer (e.g., devy) then the ownership should be transferred as well)
 KWANGHOON: It fixed. please test this.

@asdimitriadis

**Comment by rekuku** [comment] 2020-08-26 21:07
> @rekuku the pop-up dialog for selecting a bccp or asccp, when appending property, should allow the user to click on the bccp or asccp to open its detail in the new tab.

@kbserm Click DEN on the dialog opens the CC in a new window.



> The issue is that we cannot discard a revision of an ACC if we have appended some associations.
> To reproduce the issue
> 
> 1. Open an ACC which is in Published state
> 2. Create a new revision
> 3. Fill the Definition Source and Definition fields
> 4. Update the ACC
> 5. Append an ASCCP and a BCCP
> 6. Click the "Discard Revision" button.
> 
> An error is returned with the exception "java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row:"

@asdimitriadis this bug has been fixed.

**Comment by asdimitriadis** [comment] 2020-09-08 15:23
Tested and it works good. 

> @rekuku the pop-up dialog for selecting a bccp or asccp, when appending property, should allow the user to click on the bccp or asccp to open its detail in the new tab.
The "Open in a new tab" option under the menu is added instead of clicking the BCCP.

**Closed by asdimitriadis** 2020-09-08 15:23 UTC
Labels: enhancement
