### ISSUE TITLE
Reused BIE Not Updating on the User Display

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1248] opened 2022-02-14 19:25 UTC
When replacing a reused BIE, i.e. BOM Item Data inside of BOM, with a newer version of BOM Item Data, the front end display reverts back to the original reused BIE instead of the new reused BIE.  The Find BIE reuse report is showing that the new reused BIE is being reused inside of BOM, but it isn't displaying that when you open the BOM BIE in this case.  The expressed version of the BOM is showing the correct reused BIE as well.

**Comment by kbserm** [comment] 2022-02-16 11:39
@smorgan19 , have you tried clearing cache in the browser? Ctrl+shift+r on chrome

**Comment by kbserm** [comment] 2022-02-16 22:52
@asdimitriadis Could you look at reproducing this issue and work with @DimitrijeM to see if we can fix this in 2.3.

**Comment by asdimitriadis** [comment] 2022-02-17 16:52
@kbserm, @DimitrijeM I found that the issue is present when a BIE has 2 or more same BIE node reused. In this case, all reused BIE nodes are merged in the UI. 

To reproduce the issue:
1. Create two BIEs using the "BOM Item Data. BOM Item Data"
2. Make some changes to these BIEs. Be sure the changes are different so you can spot the issue easier
3. Create a BIE using the "Get BOM. Get BOM"
4. Reuse one of the BOM Item Data to the "/Get BOM/Data Area/BOM/BOM Item Data" and the other one to the "/Get BOM/Data Area/BOM/BOM Option/BOM Item Data"

At this point the values of the two reused BIE nodes are merged somehow in the UI. This happens in UI only.

**Comment by DimitrijeM** [comment] 2022-02-22 21:17
@asdimitriadis The bug fix is finished and pushed to develop, please test it.

**Comment by DimitrijeM** [comment] 2022-03-03 17:57
@asdimitriadis The bug should be fixed now. Please test it.

**Comment by asdimitriadis** [comment] 2022-03-14 02:32
It works well

**Closed by asdimitriadis** 2022-03-14 02:32 UTC
